### ISSUE TITLE
Making the App Look Good on Mobile

### ISSUE THREAD

**Issue by MarcoMorawec** [mugisha99/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

**Comment by mmugisha** [comment]
Thanks Marco for the comments! I just added the viewport tag and things look way nicer on mobile. Please let me know if that's what you had in mind.

**Comment by MarcoMorawec** [comment]
:+1: and nice work.

Looks like this commit did the trick: https://github.com/mugisha99/splurty/commit/3a88a628a8f3294c00187f5463f64a4cbabaf26a

General piece of advice for moving forward: reference specific commits or lines of codes in the comments directly, since it'll make communication a lot faster and easier.

**Comment by mmugisha** [comment]
I'll implement that advice moving forward. Thanks!

Sent from my Windows Phone
